from typing import TypedDict, List, Dict, Any, Annotated, Optional
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage

def append_reducer(left: Optional[list], right: Optional[list]) -> list:
    left = left or []
    right = right or []
    return left + right

def merge_reducer(left: Optional[dict], right: Optional[dict]) -> dict:
    left = left or {}
    right = right or {}
    return {**left, **right}

class AgentState(TypedDict):
    # Chat Messages (appended dynamically)
    messages: Annotated[List[BaseMessage], add_messages]

    
    # User original input query
    user_query: str
    
    # Active agent in the routing workflow (e.g. "supervisor", "patient_agent", "appointment_agent", etc.)
    current_agent: str
    
    # Detected user intent / classified task details
    intent: Optional[str]
    
    # Risk assessment status (e.g., low, medium, high, critical)
    risk_level: str
    
    # Current reasoning plan generated by Reasoning/Planner agent
    plan: Optional[str]
    
    # Conditional routing path
    next_step: Optional[str]
    
    # Pending tools to run
    tools_to_call: List[Dict[str, Any]]
    
    # Executed tool outcomes
    tool_results: Dict[str, Any]
    
    # Verification Agent outcome (PASSED, FAILED, PARTIAL)
    verification_status: str
    
    # Retry Counter
    retry_count: int
    
    # Human Approval gate state
    approval_required: bool
    approval_granted: bool
    approval_action: Optional[str] # "approved" or "rejected"
    
    # Final generated response back to the client
    response: Optional[str]
    
    # Metrics accumulator
    metrics: Dict[str, Any]

    # Memory Architecture states
    selected_memory_sources: List[str]
    retrieved_memories: Dict[str, Any]
    lessons_learned: Optional[str]

    # User & Thread isolation
    user_id: str
    thread_id: str
    user_role: str

    # Planner properties
    plan_steps: List[Dict[str, Any]]  # List of steps: [{"agent": "...", "tool": "..."}]
    current_step: int
    execution_plan: Optional[str]

    # Supervisor multi-agent routing
    selected_agents: List[str]               # Agents selected by supervisor (1-N)
    supervisor_confidence: float             # Supervisor routing confidence score
    supervisor_reasoning: Optional[str]      # Supervisor reasoning for agent selection

    # Verification
    verification_details: Optional[str]      # LLM fact-checking results

    # Advanced agentic architecture tracking
    agent_trace: Annotated[List[Dict[str, Any]], append_reducer]
    agent_confidence: Annotated[Dict[str, float], merge_reducer]
    citations: Annotated[List[Dict[str, Any]], append_reducer]
    agent_outputs: Annotated[List[Dict[str, Any]], append_reducer]
